# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: lightyear

before:
  hooks:
    - go mod tidy

builds:
  - id: lightyear
    main: ./cmd/lightyear
    binary: lightyear
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/nvizble/Lightyear42/cmd.Version={{.Version}}
      - -X github.com/nvizble/Lightyear42/cmd.Commit={{.ShortCommit}}
      - -X github.com/nvizble/Lightyear42/cmd.BuildDate={{.Date}}

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

nfpms:
  - id: deb
    package_name: lightyear
    homepage: https://github.com/nvizble/Lightyear42
    maintainer: João Diniz <nvizrainbow@gmail.com>
    description: |-
      CLI open source para interagir com a API oficial da 42 Network.
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    section: utils
    priority: optional
    ids:
      - lightyear
    contents:
      - src: LICENSE
        dst: /usr/share/doc/lightyear/copyright
        file_info:
          mode: 0644
      - src: README.md
        dst: /usr/share/doc/lightyear/README.md
        file_info:
          mode: 0644

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: nvizble
    name: Lightyear42
  draft: false
  prerelease: auto
  name_template: "lightyear {{.Tag}}"
